[workspace]
resolver = "3"

exclude = ["android", "nes/hdl/riscv-bios-rust"]
members = ["nes/hdmi",
    "nes/rust",
    "snes/rust",
    "controller",
]

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"  # Optimize for size.
lto = true
codegen-units = 1
