[package]
name = "nes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["sdl2"]
debugger = []
egui-multiwin = ["dep:egui", "dep:egui-multiwin", "dep:egui_glow", "dep:glutin"]
eframe = ["dep:eframe"]
sdl2 = ["dep:sdl2", "dep:egui_sdl2_gl"]

[dependencies]
rand = "0.8.5"
egui-multiwin = {version = "0.1.0", optional=true}
egui = { version = "0.19.0", optional=true }
egui_glow = { version = "0.19.0", features = ["clipboard", "winit", "links"], optional=true }
glutin = { version = "0.29.1", optional=true}
eframe = { version = "0.19.0", optional=true}
egui_sdl2_gl = { version="0.16.0", optional=true }

[dependencies.sdl2]
version="0.35.2"
features=["use_mac_framework", "image", "ttf", "mixer"]
optional=true

[dev-dependencies]
criterion = "0.3.6"

[[bench]]
name="nes_bench"
path="src/benchmark.rs"
harness = false