[package]
name = "zesty-nes"
version = "0.2.2"
authors = ["Thomas Epperson <thomas.epperson@gmail.com>"]
description = "A NES emulator written in Rust"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
debugger = []
rom_status = []
puffin = ["dep:puffin", "dep:puffin_egui"]

[dependencies]
async-channel = "2.5.0"
asynchronous-codec = "0.7.0"
biquad = "0.6.0"
bluetooth-rust = { version = "0.4.2", features = ["async"] }
chrono = "0.4.44"
common-emulator = { path = "../../common" }
controller = { path = "../../controller" }
cpal = {version = "0.17.3"}
data-encoding = "2.11.0"
directories = "6.0.0"
enum_dispatch = "0.3.13"
gilrs = {version = "0.11.1", features = ["serde-serialize"]}
hex_fmt = "0.3.0"
libp2p = { version = "0.56", features = ["tokio", "dns", "macros", "noise", "tcp", "upnp", "yamux", "serde"] }
log = "0.4.30"
simple_logger = "5.2.0"

#update later
rand = "0.8.5" 
ringbuf = "0.3.3"

egui = { version = "0.34.2", features = ["serde"] }
eframe = { version = "0.34.2" }
futures = "0.3.32"
gstreamer = "0.25.2"
gstreamer-app = "0.25.2"
gstreamer-audio = "0.25.2"
gstreamer-video = "0.25.2"
memmap2 = "0.9.10"
open = "5.3.5"
puffin = { version = "0.20", optional=true}
puffin_egui = { version = "0.30", optional=true }
rfd = "0.17.2"
ring = "0.17.14"
strum = { version = "0.28", features = ["derive"] }
tokio = { version = "1.52.3", features = ["full"] }
toml = "1.1.2"
walkdir = "2.5"
serde = {version = "1.0.228", features = ["derive"]}
serde_with = "3.20"
bincode = "1.3.3"

[dev-dependencies]
criterion = "0.8.2"

[[bench]]
name="nes_bench"
path="src/benchmark.rs"
harness = false

[[bin]]
name = "zesty-nes"
path = "./src/main.rs"

[[bin]]
name = "stream"
path = "./src/streamtest.rs"

[package.metadata.bundle]
identifier = "com.uglyoldbob.nes_emulator"

[package.metadata.deb]
assets = [
    ["target/release/zesty-nes", "usr/bin/", "755"],
    ["zestynes.png", "/usr/share/icons/hicolor/256x256/apps/zestynes.png", "444"],
    ["com.uglyoldbob.ZestyNes.desktop", "/usr/share/applications/com.uglyoldbob.ZestyNes.desktop", "644"],
]
depends = ["libgstreamer1.0-0",
    "libgstreamer-plugins-base1.0-0",
    "libgstreamer-plugins-bad1.0-0",
    "libopenh264-7",
    "gstreamer1.0-plugins-good",
    "gstreamer1.0-plugins-base",
    "gstreamer1.0-plugins-bad",
    ]