name: IOS Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install LLVM
      run: brew install llvm
    - name: Checkout xbuild
      run: git clone https://gitlab.com/thomas.epperson/xbuild.git
    - name: Setup 'xbuild'
      working-directory: ./xbuild/xbuild
      run: cargo install --path .
    - name: Build with xbuild
      working-directory: ./nes/rust
      run: x build --platform=ios --arch=arm64
