name: IOS Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Debug for linking
      run: xcrun --sdk iphoneos swiftc -print-target-info
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install LLVM
      run: brew install llvm
    - name: Setup LLVM vars
      run: |
        echo "/opt/homebrew/opt/llvm/bin" >> $GITHUB_PATH
        echo LDFLAGS="-L/opt/homebrew/opt/llvm/lib" >> $GITHUB_ENV
        echo CPPFLAGS="-I/opt/homebrew/opt/llvm/include" >> $GITHUB_ENV
    - name: Verify LLVM tools
      run: |
        which llvm-ar
        llvm-ar --version
    - name: Checkout xbuild
      run: git clone https://gitlab.com/thomas.epperson/xbuild.git
    - name: Setup 'xbuild'
      working-directory: ./xbuild/xbuild
      run: cargo install --path .
    - name: Build with xbuild
      working-directory: ./nes/rust
      run: x build --platform=ios --arch=arm64
