name: OSX Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install build dependencies
      run: |
        brew update
    - name: Build
      run: cargo build --verbose
