name: Windows Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install GStreamer
      uses: blinemedical/setup-gstreamer@v1
      with:
        version: '1.22.7'
    - name: Set PKG_CONFIG_PATH
      run: |
        echo "PKG_CONFIG_PATH=C:\gstreamer\1.0\msvc_x86_64\lib\pkgconfig" >> $env:GITHUB_ENV
    - name: Build
      working-directory: ./nes/rust
      run: cargo build --verbose --bin zesty-nes
